### PR TITLE
Retire a site and replace with a new one.

### PR DESCRIPTION
**Pull request by smth**

### CODE REVIEW

**Comment by Snapstromegon** [comment]
Hi @smth,
the hash of the file is based on the url, so doing this like you did here sadly doesn't work correctly.
I'd like to ask you to create a PR that removes this file and to add an issue that adds the new url as a new page, so everything can be handled correctly by our automations.

**Comment by smth** [comment]
OK. I did wonder, but then realised I did [a similar thing](https://github.com/11ty/11ty-community/pull/456) a year ago and that seemed fine?

**Comment by Snapstromegon** [comment]
I wasn't a member of the 11ty Github Org back then, so I can't say why it was handled that way.
As far as I know, the method I descibed above is right now the preferred method of updating an URL for this project.

**Comment by smth** [comment]
File now deleted in this PR.

**Pull request merged**
